/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pedro_metadatavideo_VideoInjector */

#ifndef _Included_com_pedro_metadatavideo_VideoInjector
#define _Included_com_pedro_metadatavideo_VideoInjector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pedro_metadatavideo_VideoInjector
 * Method:    injectVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pedro_metadatavideo_VideoInjector_injectVideo
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
